routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//    Frontend page route
Route::get('/', 'HomepageController@index')->name('homepage');
Route::get('/all_doctors', 'HomepageController@all_doctors');
Route::get('/doctor_details/{slug}', 'HomepageController@doctor_details');

Route::get('/all_departments', 'HomepageController@all_departments');
Route::get('/department_details/{slug}', 'HomepageController@department_details');

Route::get('/contact','HomepageController@contact');
Route::resource('contact_us','ContactUsController');
Route::get('/about','HomepageController@about');
Route::get('/search','HomepageController@search')->name('search');

Route::resource('feedback','FeedbackController');

Route::resource('appoinment','AppoinmentController');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

//    For Admin
Route::group([ 'as'=> 'admin.','prefix'=> 'admin', 'namespace'=> 'Admin', 'middleware'=>['auth','admin']], function (){

    Route::get('/dashboard','DashboardController@index')->name('dashboard');
    Route::resource('/department','DepartmentController');
    Route::resource('/payments','PaymentController');

    Route::get('/doctor/details/{id}','DashboardController@doctor_details');
    Route::post('/doctor_confirm/{id}','DashboardController@doctor_confirm')->name('doctor_confirm');
    Route::get('/doctor/all','DashboardController@all_doctors');

    Route::post('/appoinment_confirm_paid/{id}','DashboardController@confirm_paid')->name('confirm_paid');
    Route::get('/appoinments/all','DashboardController@all_appoinments');
    Route::delete('/appoinments/delete/{id}','DashboardController@delete_appoinments')->name('appoinment.delete');

    Route::get('/patient/all','PatientsController@index');
    Route::get('/patient/details/{id}','PatientsController@patient_details');

});

//    For Doctor
Route::group([ 'as'=> 'doctor.','prefix'=> 'doctor', 'namespace'=> 'Doctor', 'middleware'=>['auth','doctor']], function (){

    Route::get('/dashboard','DashboardController@index')->name('dashboard');
    Route::get('/profile','DashboardController@profile')->name('profile');
    Route::post('/profile/update/{id}','DashboardController@profile_update')->name('profile.update');
    Route::get('/appoinments/{id}','DashboardController@appoinment_details');
    Route::get('/mypatients','DashboardController@mypatients');
    Route::post('/appoinment/update/{id}','DashboardController@cancel_appoinment')->name('appoinment.update');
    Route::post('/appoinment/confirm/{id}','DashboardController@confirm_appoinment')->name('appoinment.confirm');

    Route::post('/prescriptions/','DashboardController@send_prescription')->name('prescription.store');

});

//    For Patient
Route::group([ 'as'=> 'patient.','prefix'=> 'patient', 'namespace'=> 'Patient', 'middleware'=>['auth','patient']], function (){

    Route::get('/dashboard','DashboardController@index')->name('dashboard');
    Route::get('/profile','DashboardController@profile')->name('profile');
    Route::get('/prescription','DashboardController@my_prescription')->name('prescription');
    Route::post('/profile/update/{id}','DashboardController@profile_update')->name('profile.update');

});

app/Http/Controllers/Admin/PaymentController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Model\Payment;
use Illuminate\Http\Request;

class PaymentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $payments = Payment::all();
        return view('admin.pages.payment.index', compact('payments'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $payment = new Payment();

        $payment->name = $request->name;
        $payment->short_name = str_slug($request->name);
        $payment->type = $request->type;
        $payment->no = $request->no;

        if($request['payment_image']){

            $path = public_path().'/payments/';
            //upload new file
            $image = $request->payment_image;
            $imagename = time().'.'.$image->extension();
            $image->move($path, $imagename);

        }
        $payment->image = $imagename;

        $payment->save();
        return redirect()->back()->with('message', 'Payment added Successfully.');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $payment = Payment::find($id);
        if (!is_null($payment)) {
            return view('admin.pages.payment.edit', compact('payment'));
        } else {
            return redirect()->route('admin.payments.index');
        }

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $payment = Payment::where('id',$id)->get()->first();

        if($request->payment_image != ''){
            $this->validate($request,[
                'payment_image' => 'required|image|mimes:jpeg,png,jpg,gif,svg|max:2048',
            ],
                [
                    'payment_image.image'=>'Provide a valid image.',
                ]
            );

            $path = public_path().'/payments/'  ;

            //code for remove old file
            if($payment->image != ''  && $payment->image != null){
                $file_old = $path.$payment->image;
                unlink($file_old);
            }

            //upload new file
            $image = $request->payment_image;
            $imagename = time().'.'.$image->extension();
            $image->move($path, $imagename);

            $payment->update(['image' => $imagename]);
        }

        $payment['name'] = $request->name;
        $payment['short_name'] = str_slug($request->name);
        $payment['type'] = $request->type;
        $payment['no'] = $request->no;

        $payment->update();
        return redirect()->back()->with('message', 'Payment method Updated Successfully.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $payment = Payment::where('id',$id)->get()->first();
        $path = public_path().'/payments/';
        //code for remove old file
        if($payment->image != ''  && $payment->image != null){
            $file_old = $path.$payment->image;
            unlink($file_old);
        }

        $payment->delete();
        return redirect()->back()->with('message', 'Payment method deleted Successfully.');
    }
}

resources/views/admin/pages/payment/edit.blade.php
@extends('admin.layouts.admin_layout')

@section('content')

    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">Dashboard</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{{ url('/admin/dashboard/') }}">Dashboard</a></li>
                        <li class="breadcrumb-item"><a href="{{route('admin.payments.index') }}">Payment</a></li>
                        <li class="breadcrumb-item active">Payment Edit</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="card p-4">
                        <form method="POST" action="{{ route('admin.payments.update',$payment->id) }}" enctype="multipart/form-data">
                            @csrf
                            @method('put')
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label for="name">{{ __('Payment Name') }}</label>
                                        <input id="name" type="text"
                                               class="form-control @error('name') is-invalid @enderror" name="name"
                                               value="{{ $payment->name }}" required autocomplete="name" autofocus placeholder="Enter name...">
                                        @error('name')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                        @enderror
                                    </div>

                                    <div class="form-group">
                                        <label for="email">{{ __('Payment Account No.') }}</label>
                                        <input id="icon" type="text"
                                               class="form-control @error('icon') is-invalid @enderror" name="no"
                                               value="{{ $payment->no }}" required autocomplete="no" placeholder="Enter account number..." maxlength="12">
                                        @error('no')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                        @enderror
                                    </div>

                                    <div class="form-group">
                                        <label for="email">{{ __('Payment Account Type.') }}</label>

                                        <select name="type" id="type" class="form-control @error('type') is-invalid @enderror">
                                            <option value="">Select Account Type</option>
                                            <option value="agent" {{ $payment->type =='agent'?'selected':'' }}>Agent</option>
                                            <option value="personal" {{ $payment->type =='personal'?'selected':'' }}>Personal</option>
                                        </select>
                                        @error('type')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                        @enderror
                                    </div>


                                    <div class="form-group">
                                        <label for="customFile">{{ __('Payment Image') }}</label>

                                        <div class="custom-file">
                                            <input type="file" name="payment_image" class="custom-file-input" id="customFile">
                                            <label class="custom-file-label" for="customFile"></label>
                                        </div>
                                        @error('payment_image')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                        @enderror
                                    </div>
                                    <div class="form-group">
                                        {{--<label for="">{{ __('Old Image') }} : </label>--}}
                                        <img src="{{ asset('public/payments/'.$payment->image) }}" alt="" class="img-fluid" style="width: 200px; height: 100px">
                                    </div>
                                </div>
                            </div>
                            <button type="submit" id="register" class="btn btn-info bg-one float-right">{{ __('Update Payment Method') }}</button>
                        </form>
                    </div>
                </div>

            </div>
            <!-- /.row -->

        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content -->
@endsection

resources/views/admin/pages/payment/index.blade.php
@extends('admin.layouts.admin_layout')

@section('content')

<!-- Content Header (Page header) -->
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0 text-dark">Payments</h1>
            </div><!-- /.col -->
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="{{ url('/admin/dashboard/') }}">Dashboard</a></li>
                    <li class="breadcrumb-item active">Payments</li>
                </ol>
            </div><!-- /.col -->
        </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</div>
<!-- /.content-header -->

<!-- Main content -->
<div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">

                <div class="card card-outline card-info">
                    <div class="card-header">
                        <div class="row">
                            <div class="col-6">
                                <h4 class="">All Payments Method</h4>
                            </div>
                            <div class="col-6">
                                <a href="" class="btn btn-primary  float-right" data-toggle="modal" data-target="#register"> <i class="fas fa-plus-circle" aria-hidden="true"></i>
                                    Add New Payment
                                </a>
                            </div>
                        </div>

                    </div>
                    <!-- /.card-header -->
                    <div class="card-body">
                        <table id="admin_datatable" class="table table-bordered table-striped " >
                            <thead>
                            <tr>
                                <th>SN</th>
                                <th>Name</th>
                                <th>Image</th>
                                <th>Account No</th>
                                <th style="width: 40px">Action</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($payments as $payment)
                                <tr>
                                    <td class="align-middle text-center">{{ $loop->index+1 }}</td>
                                    <td class="align-middle text-center">{{ $payment->name }}</td>
                                    <td class="align-middle text-center"> <img src="{{ asset('public/payments/'.$payment->image) }}" alt="" style="width: 200px;height: 100px"></td>
                                    <td class="align-middle text-center"> {{ $payment->no }}</td>
                                    <td class="align-middle text-center">
                                        <div class="btn-group mr-2" role="group" aria-label="First group">
                                            <a href="{{ route('admin.payments.edit', $payment->id ) }}"
                                               class="btn btn-success btn-sm" data-toggle="tooltip" data-placement="top" title="Edit or View"><i class="fas fa-edit"></i></a>

                                            <span class="btn btn-danger btn-sm" data-toggle="tooltip" data-placement="top" title="Delete">
                                            <a href="#deleteModal{{$payment->id}}" class="text-white"
                                               data-toggle="modal" ><i class="fas fa-trash"></i></a>
                                             </span>
                                            <!-- Delete Modal -->
                                            <div class="modal fade" id="deleteModal{{$payment->id}}" tabindex="-1"
                                                 role="dialog" aria-hidden="true">
                                                <div class="modal-dialog" role="document">
                                                    <div class="modal-content">
                                                        <div class="modal-body">
                                                            <h4>Are You Sure to Delete ?</h4>
                                                        </div>
                                                        <div class="modal-footer">
                                                            <form action="{{route('admin.payments.destroy', $payment->id)}}"
                                                                  method="post">
                                                                @csrf
                                                                @method('delete')
                                                                <button type="submit" class="btn btn-danger">Ok
                                                                </button>
                                                            </form>
                                                            <button type="button" class="btn btn-warning"
                                                                    data-dismiss="modal">Cancel
                                                            </button>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>

                        </table>
                    </div>
                    <!-- /.card-body -->
                </div>
                <!-- /.card -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </div>
    <!-- /.container-fluid -->
</div>
<!-- /.content -->


<!--For add new payment -->
<div class="modal fade" id="register" tabindex="-1" role="dialog" aria-labelledby="register" aria-hidden="true">
    <div class="modal-dialog " role="document" >
        <div class="modal-content">
            <div class="modal-header bg-info">
                <h5 class="modal-title text-white" id="register">Add New Payments</h5>
                <button type="button" class="close text-white" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body p-4">
                <form method="POST" action="{{ route('admin.payments.store') }}" enctype="multipart/form-data">
                    @csrf
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label for="name">{{ __('Payment Name') }}</label>
                                <input id="name" type="text"
                                       class="form-control @error('name') is-invalid @enderror" name="name"
                                       value="{{ old('name') }}" required autocomplete="name" autofocus placeholder="Enter name...">
                                @error('name')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                                @enderror
                            </div>

                            <div class="form-group">
                                <label for="email">{{ __('Payment Account No.') }}</label>
                                <input id="icon" type="text"
                                       class="form-control @error('icon') is-invalid @enderror" name="no"
                                       value="{{ old('no') }}" required autocomplete="no" placeholder="Enter account number..." maxlength="12">
                                @error('no')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                                @enderror
                            </div>

                            <div class="form-group">
                                <label for="email">{{ __('Payment Account Type.') }}</label>

                                <select name="type" id="type" class="form-control @error('icon') is-invalid @enderror">
                                    <option value="">Select Account Type</option>
                                    <option value="agent">Agent</option>
                                    <option value="personal">Personal</option>
                                </select>
                                @error('no')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                                @enderror
                            </div>

                            <div class="form-group">
                                <label for="customFile">{{ __('Payment Image') }}</label>

                                <div class="custom-file">
                                    <input type="file" name="payment_image" class="custom-file-input" id="customFile">
                                    <label class="custom-file-label" for="customFile"></label>
                                </div>
                                @error('payment_image')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                                @enderror
                            </div>
                        </div>
                    </div>

                    <button type="submit" id="register" class="btn btn-info bg-one">{{ __('Add Payment') }}</button>
                </form>
            </div>
        </div>
    </div>
</div>

@endsection