routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//    Frontend page route
Route::get('/', 'HomepageController@index')->name('homepage');
Route::get('/all_doctors', 'HomepageController@all_doctors');
Route::get('/doctor_details/{slug}', 'HomepageController@doctor_details');

Route::get('/all_departments', 'HomepageController@all_departments');
Route::get('/department_details/{slug}', 'HomepageController@department_details');

Route::get('/contact','HomepageController@contact');
Route::resource('contact_us','ContactUsController');
Route::get('/about','HomepageController@about');
Route::get('/search','HomepageController@search')->name('search');

Route::resource('feedback','FeedbackController');

Route::resource('appoinment','AppoinmentController');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

//    For Admin
Route::group([ 'as'=> 'admin.','prefix'=> 'admin', 'namespace'=> 'Admin', 'middleware'=>['auth','admin']], function (){

    Route::get('/dashboard','DashboardController@index')->name('dashboard');
    Route::resource('/department','DepartmentController');
    Route::resource('/payments','PaymentController');

    Route::get('/doctor/details/{id}','DashboardController@doctor_details');
    Route::post('/doctor_confirm/{id}','DashboardController@doctor_confirm')->name('doctor_confirm');
    Route::get('/doctor/all','DashboardController@all_doctors');

    Route::post('/appoinment_confirm_paid/{id}','DashboardController@confirm_paid')->name('confirm_paid');
    Route::get('/appoinments/all','DashboardController@all_appoinments');
    Route::delete('/appoinments/delete/{id}','DashboardController@delete_appoinments')->name('appoinment.delete');

    Route::get('/patient/all','PatientsController@index');
    Route::get('/patient/details/{id}','PatientsController@patient_details');

});

//    For Doctor
Route::group([ 'as'=> 'doctor.','prefix'=> 'doctor', 'namespace'=> 'Doctor', 'middleware'=>['auth','doctor']], function (){

    Route::get('/dashboard','DashboardController@index')->name('dashboard');
    Route::get('/profile','DashboardController@profile')->name('profile');
    Route::post('/profile/update/{id}','DashboardController@profile_update')->name('profile.update');
    Route::get('/appoinments/{id}','DashboardController@appoinment_details');
    Route::get('/mypatients','DashboardController@mypatients');
    Route::post('/appoinment/update/{id}','DashboardController@cancel_appoinment')->name('appoinment.update');
    Route::post('/appoinment/confirm/{id}','DashboardController@confirm_appoinment')->name('appoinment.confirm');

    Route::post('/prescriptions/','DashboardController@send_prescription')->name('prescription.store');

});

//    For Patient
Route::group([ 'as'=> 'patient.','prefix'=> 'patient', 'namespace'=> 'Patient', 'middleware'=>['auth','patient']], function (){

    Route::get('/dashboard','DashboardController@index')->name('dashboard');
    Route::get('/profile','DashboardController@profile')->name('profile');
    Route::get('/prescription','DashboardController@my_prescription')->name('prescription');
    Route::post('/profile/update/{id}','DashboardController@profile_update')->name('profile.update');

});

app/Http/Controllers/Admin/PatientsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Model\Patient;
use Illuminate\Http\Request;

class PatientsController extends Controller
{

    public function index(){
        $patients = Patient::orderBy('user_id','asc')->get();
        return view('admin.pages.patients.all_patients',compact('patients'));
    }

    public function patient_details($id=null){
        $patient = Patient::find($id);
        return view('admin.pages.patients.patient_details',compact('patient'));
    }

}

app/Http/Controllers/Patient/DashboardController.php
<?php

namespace App\Http\Controllers\Patient;

use App\Http\Controllers\Controller;
use App\Model\Appoinment;
use App\Model\Feedback;
use App\Model\Patient;
use App\Model\Prescription;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class DashboardController extends Controller
{

    public function index(){
        $id = Auth::user()->id;
        $patient = User::where('id',$id)->first();
        $patient_id = $patient->patient->id;

        $my_total_appoinments = Appoinment::where('patient_id',$patient_id)->count();
        $my_total_feedbacks = Feedback::where('user_id',$id)->count();

        $appoinments = Appoinment::where('patient_id',$patient_id)->orderBy('id','asc')->get();
        return view('patient.dashboard', compact('patient','appoinments','my_total_appoinments','my_total_feedbacks'));
    }

    public function profile(){
        $id = Auth::user()->id;
        $patient = User::where('id',$id)->first();
        return view('patient.profile.index', compact('patient'));
    }


    public function profile_update(Request $request,$id){


        $patient = Patient::where('id',$id)->get()->first();

        if($request->avatar != ''){
            $this->validate($request,[
                'avatar' => 'required|image|mimes:jpeg,png,jpg,gif,svg|max:2048',
            ],
                [
                    'avatar.image'=>'Provide a valid image.',
                ]
            );

            $path = public_path().'/patients/avatar/';

            //code for remove old file
            if($patient->avatar != ''  && $patient->avatar != null){
                $file_old = $path.$patient->avatar;
                unlink($file_old);
            }

            //upload new file
            $image = $request->avatar;
            $imagename = time().'.'.$image->extension();
            $image->move($path, $imagename);

            //for update in table
//            $doctor->update(['avatar' => $imagename]);

//            $doctor['avatar'] = $request->imagename;
            $patient->update(['avatar' => $imagename]);
        }

        $patient['father_name'] = $request->father_name;
        $patient['mobile_no'] = $request->mobile_no;
        $patient['date_of_birth'] = $request->date_of_birth;
        $patient['age'] = $request->age;
        $patient['gender'] = $request->gender;
        $patient['occupation'] = $request->occupation;
        $patient['maritial_status'] = $request->maritial_status;
        $patient['religion'] = $request->religion;
        $patient['blood_group'] = $request->blood_group;
        $patient['address'] = $request->address;

        $patient->update();

        return redirect()->back()->with('message', 'Patient information Updated Successfully.');

    }


    public function my_prescription(){
        $id = Auth::user()->id;
        $patient = User::where('id',$id)->first();
        $pid = $patient->patient->id;
        $my_prescriptions = Prescription::where('patient_id',$pid)->get();

        return view('patient.prescription.index', compact('my_prescriptions','patient'));


    }


}

resources/views/admin/pages/patients/all_patients.blade.php
@extends('admin.layouts.admin_layout')

@section('content')

    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">Patient Details</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{{ url('admin/dashboard') }}">Dashboard</a></li>
                        <li class="breadcrumb-item active">Patient details</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <div class="content">
        <div class="container-fluid">


            <div class="row">
                <div class="col-md-12">
                    <div class="card ">
                        <div class="card-header card-outline  card-primary">

                              <h4 class="card-title ">All Patients</h4>
                              <div class="card-tools">
                                  <button type="button" class="btn btn-tool" data-card-widget="collapse">
                                      <i class="fas fa-minus"></i>
                                  </button>
                              </div>

                        </div>
                        <!-- /.card-header -->
                    <div class="card-body " style="display: block;">
                            <div class="table-responsive">
                                <table id="admin_datatable" class="table table-striped border m-0">
                                    <thead>
                                    <tr>
                                        <th>Patient ID</th>
                                        <th>Name</th>
                                        <th>Avatar</th>
                                        <th>Gender</th>
                                        <th>age</th>
                                        <th style="width:150px;">Mobile</th>
                                        <th class="text-center" style="width:100px;">Action</th>
                                    </tr>
                                    </thead>
                                    <tbody>

                                    @foreach($patients as $patient)
                                        <tr>
                                            <td><a href="{{ url('admin/patient/details/'.$patient->id) }}">SMCP122{{ $loop->index+1 }}</a></td>
                                            <td>{{ $patient->user->name }} </td>
                                            <td>
                                                <img src="{{ asset('public/patients/avatar/'.$patient->avatar) }}" alt="" class="img-fluid" style="height: 100px">
                                            </td>
                                            <td>{{ @$patient->gender }} </td>
                                            <td>{{ @$patient->age }} </td>
                                            <td>{{ @$patient->mobile_no }} </td>
                                            <td class="text-center">
                                                <div class="btn-group mr-2" role="group" aria-label="First group">
                                                    <a href="{{ url('admin/patient/details/'.$patient->id) }}"
                                                       class="btn btn-primary btn-sm"><i class="fas fa-eye"></i></a>
                                                    <a href="#deleteModal{{$patient->id}}" class="btn btn-danger btn-sm"
                                                       data-toggle="modal"><i class="fas fa-trash"></i></a>

                                                    <!-- Delete Modal -->
                                                    <div class="modal fade" id="deleteModal{{$patient->id}}" tabindex="-1"
                                                         role="dialog" aria-hidden="true">
                                                        <div class="modal-dialog" role="document">
                                                            <div class="modal-content">
                                                                <div class="modal-body">
                                                                    <h4>Are You Sure to Delete ?</h4>
                                                                </div>
                                                                <div class="modal-footer">
                                                                    <form action="" method="post">
                                                                        {{ csrf_field() }}
                                                                        <button type="button" class="btn btn-danger">Ok
                                                                        </button>
                                                                    </form>
                                                                    <button type="button" class="btn btn-warning" data-dismiss="modal">Cancel
                                                                    </button>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </td>

                                        </tr>
                                    @endforeach

                                    </tbody>
                                </table>
                            </div>
                            <!-- /.table-responsive -->
                        </div>
                        <!-- /.card-body -->
                        <div class="card-footer clearfix" style="display: block;">

                            <a href="javascript:void(0)" class="btn btn-sm btn-primary float-right">View All Patients</a>
                        </div>
                        <!-- /.card-footer -->
                    </div>
                </div>
            </div>

        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content -->
@endsection

resources/views/admin/pages/patients/patient_details.blade.php
@extends('admin.layouts.admin_layout')

@section('content')

<!-- Content Header (Page header) -->
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0 text-dark">Patient Details</h1>
            </div><!-- /.col -->
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="{{ url('admin/dashboard') }}">Dashboard</a></li>
                    <li class="breadcrumb-item active">Patient details</li>
                </ol>
            </div><!-- /.col -->
        </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</div>
<!-- /.content-header -->

<!-- Main content -->
<div class="content">
    <div class="container-fluid">
       <div class="card card-outline">
           <h5 class="text-center card-header bg-light  text-success text-uppercase">Basic Info</h5>
              <div class="card-body">
                  <div class="row">
                      <div class="col-sm-12 col-md-4">
                          <div class="">
                              <img src="{{ asset('public/patients/avatar/'.$patient->avatar) }}" alt="doctor photo" class="img-fluid img-thumbnail" style="height: 250px; width: 100%;">
                          </div>
                      </div>
                      <div class="col-sm-12 col-md-8 d-flex justify-content-end">
                          <div class="text-right w-75">
                              <h3  class="text-primary text-capitalize">{{ $patient->user->name }}</h3>
                              <h6 class="text-danger">{{ $patient->occupation }}</h6>
                              <h6 class="text-info">{!! $patient->address !!}</h6>
                              <table class="table w-100 ml-auto table-striped mt-2 mb-0 text-muted">
                                  <tbody>
                                  <tr>
                                      <td scope="row"  class="border-top-0 text-left">
                                          <span><i class="fas fa-envelope"></i> Email :</span>
                                      </td>
                                      <td class="border-top-0" > {{ $patient->user->email }}</td>
                                  </tr>
                                  <tr>
                                      <td scope="row" class="text-left">
                                          <span><i class="fas fa-phone fa-rotate-90"></i> Phone :</span>
                                      </td>
                                      <td> {{ $patient->mobile_no }}</td>
                                  </tr>
                                  <tr>
                                      <td scope="row" class="text-left">
                                          <span> <i class="fas fa-money-bill"></i> Age :</span>
                                      </td>
                                      <td> {{ $patient->age }} Years</td>
                                  </tr>

                                  </tbody>
                              </table>

                          </div>
                      </div>
                  </div>
              </div>
       </div>
{{--        <div class="doctors_info_editor">
            <div class="row mt-3">
                <div class="col-12">
                    <div class="card border-0">
                        <h5 class="text-center card-header bg-light text-success text-uppercase">Work & Education Info</h5>
                        <div class="card-body">
                            <div class=" text-muted">
                                {!!  $doctor->describe_yourself !!}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row mt-3">
                <div class="col-12">
                    <div class="card border-0 ">
                        <h5 class="text-center card-header bg-light text-success text-uppercase">Chamber and Schedule</h5>
                        <div class="card-body">
                            <div class="text-muted">
                                {!! $doctor->doctor->chamber_information  !!}
                            </div>
                        </div>
                        <div class="card-footer clearfix" style="display: block;">

                            <form action="{{ route('admin.doctor_confirm', $doctor->doctor->id) }}" method="post">
                                @csrf
                                @if($doctor->doctor->status)
                                    <input type="submit" class="float-right btn btn-success" value="Verified">
                                @else
                                    <input type="submit" class="float-right btn btn-primary " value="Confirm Now">
                                @endif

                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>--}}
    </div><!-- /.container-fluid -->
</div>
<!-- /.content -->
@endsection