routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//    Frontend page route
Route::get('/', 'HomepageController@index')->name('homepage');
Route::get('/all_doctors', 'HomepageController@all_doctors');
Route::get('/doctor_details/{slug}', 'HomepageController@doctor_details');

Route::get('/all_departments', 'HomepageController@all_departments');
Route::get('/department_details/{slug}', 'HomepageController@department_details');

Route::get('/contact','HomepageController@contact');
Route::resource('contact_us','ContactUsController');
Route::get('/about','HomepageController@about');
Route::get('/search','HomepageController@search')->name('search');

Route::resource('feedback','FeedbackController');

Route::resource('appoinment','AppoinmentController');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

//    For Admin
Route::group([ 'as'=> 'admin.','prefix'=> 'admin', 'namespace'=> 'Admin', 'middleware'=>['auth','admin']], function (){

    Route::get('/dashboard','DashboardController@index')->name('dashboard');
    Route::resource('/department','DepartmentController');
    Route::resource('/payments','PaymentController');

    Route::get('/doctor/details/{id}','DashboardController@doctor_details');
    Route::post('/doctor_confirm/{id}','DashboardController@doctor_confirm')->name('doctor_confirm');
    Route::get('/doctor/all','DashboardController@all_doctors');

    Route::post('/appoinment_confirm_paid/{id}','DashboardController@confirm_paid')->name('confirm_paid');
    Route::get('/appoinments/all','DashboardController@all_appoinments');
    Route::delete('/appoinments/delete/{id}','DashboardController@delete_appoinments')->name('appoinment.delete');

    Route::get('/patient/all','PatientsController@index');
    Route::get('/patient/details/{id}','PatientsController@patient_details');

});

//    For Doctor
Route::group([ 'as'=> 'doctor.','prefix'=> 'doctor', 'namespace'=> 'Doctor', 'middleware'=>['auth','doctor']], function (){

    Route::get('/dashboard','DashboardController@index')->name('dashboard');
    Route::get('/profile','DashboardController@profile')->name('profile');
    Route::post('/profile/update/{id}','DashboardController@profile_update')->name('profile.update');
    Route::get('/appoinments/{id}','DashboardController@appoinment_details');
    Route::get('/mypatients','DashboardController@mypatients');
    Route::post('/appoinment/update/{id}','DashboardController@cancel_appoinment')->name('appoinment.update');
    Route::post('/appoinment/confirm/{id}','DashboardController@confirm_appoinment')->name('appoinment.confirm');

    Route::post('/prescriptions/','DashboardController@send_prescription')->name('prescription.store');

});

//    For Patient
Route::group([ 'as'=> 'patient.','prefix'=> 'patient', 'namespace'=> 'Patient', 'middleware'=>['auth','patient']], function (){

    Route::get('/dashboard','DashboardController@index')->name('dashboard');
    Route::get('/profile','DashboardController@profile')->name('profile');
    Route::get('/prescription','DashboardController@my_prescription')->name('prescription');
    Route::post('/profile/update/{id}','DashboardController@profile_update')->name('profile.update');

});

app/Http/Controllers/Doctor/DashboardController.php
<?php

namespace App\Http\Controllers\Doctor;

use App\Http\Controllers\Controller;
use App\Model\Appoinment;
use App\Model\Department;
use App\Model\Doctor;
use App\Model\Feedback;
use App\Model\Prescription;
use App\Role;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class DashboardController extends Controller
{

    public function index(){
        $id = Auth::user()->id;
        $doctor = User::where('id',$id)->first();

        $doctor_id = $doctor->doctor->id;
        $totalAppoinment = Appoinment::Where('doctor_id',$doctor_id)->get()->count();
        $totalFeedback = Feedback::Where('doctor_id',$doctor_id)->get()->count();

        $appoinments = Appoinment::where('doctor_id',$doctor_id)->where('status', '!=',1)->orderBy('id','asc')->get();

        return view('doctor.dashboard', compact('doctor','appoinments','totalAppoinment','totalFeedback'));
    }

    public function profile(){
        $id = Auth::user()->id;
        $doctor = User::where('id',$id)->first();
        $departments = Department::orderBy('name','asc')->get();
        return view('doctor.profile.index', compact('doctor','departments'));
    }


    public function profile_update(Request $request,$id){


        $doctor = Doctor::where('id',$id)->get()->first();

        if($request->photo != ''){
            $this->validate($request,[
                'photo' => 'required|image|mimes:jpeg,png,jpg,gif,svg|max:2048',
            ],
                [
                'photo.image'=>'Provide a valid image.',
                ]
            );

            $path = public_path().'/doctors/avatar/';

            //code for remove old file
            if($doctor->photo != ''  && $doctor->photo != null){
                $file_old = $path.$doctor->photo;
                unlink($file_old);
            }

            //upload new file
            $image = $request->photo;
            $imagename = time().'.'.$image->extension();
            $image->move($path, $imagename);

            //for update in table
//            $doctor->update(['photo' => $imagename]);

//            $doctor['photo'] = $request->imagename;
            $doctor->update(['photo' => $imagename]);
        }

        $doctor['title'] = $request->title;
        $doctor['department_id'] = $request->department_id;
        $doctor['phone'] = $request->phone;
        $doctor['year_of_experience'] = $request->year_of_experience;
        $doctor['fees'] = $request->fees;
        $doctor['describe_yourself'] = $request->describe_yourself;
        $doctor['chamber_information'] = $request->chamber_information;

        $doctor->update();
        return redirect()->back()->with('message', 'User Updated Successfully.');

    }

    public function appoinment_details($id){
        $did = Auth::user()->id;
        $doctor = User::where('id',$did)->first();
        $appoinment = Appoinment::where('id',$id)->orderBy('id','asc')->first();
        return view('doctor.appoinments.index', compact('doctor','appoinment'));
    }



    public function cancel_appoinment($id){

        $appoinment = Appoinment::find($id);

        $appoinment->cancel_by_doctor = 1;
        $appoinment->status = 3;

        $appoinment->save();

        Session()->flash('message', 'Appoinment has been cancel successfully');
        return redirect()->back();
    }

    public function confirm_appoinment($id){
        $appoinment = Appoinment::find($id);

        $appoinment->status = 1;

        $appoinment->save();

        Session()->flash('message', 'Appoinment has been confirm successfully');
        return redirect()->back();
    }

    public function mypatients(){
        $id = Auth::user()->id;
        $doctor = User::where('id',$id)->first();

        $doctor_id = $doctor->doctor->id;

        $mypatients = Appoinment::where('doctor_id',$doctor_id)->where('status', '=', 1)->orderBy('id','asc')->get();

        return view('doctor.mypatients.all_patients', compact('doctor','mypatients'));

    }


    public function send_prescription(Request $request){

        $prescription = new Prescription();

        if($request->prescription != ''){
            $this->validate($request,[
                'prescription' => 'required|image|mimes:jpeg,png,jpg,gif,svg|max:2048',
            ],
                [
                    'prescription.image'=>'Provide a valid image.',
                ]
            );

            $path = public_path().'/prescriptions/';

            //upload new file
            $image = $request->prescription;
            $imagename = time().'.'.$image->extension();
            $image->move($path, $imagename);

            $prescription['prescription'] = $imagename;
        }

        $prescription['doctor_id'] = $request->doctor_id;
        $prescription['patient_id'] = $request->patient_id;

        $prescription->save();
        return redirect()->back()->with('message', 'Prescription send Successfully.');

    }



}

resources/views/doctor/profile/index.blade.php
@extends('doctor.layout.doctor_layout')

@section('doctor_content')
    <div class="">
        <div class="row align-items-center">
            <div class="col-md-6">
                <h6 class="text-capitalize mb-0 text-dark">
                    My Profile
                </h6>
            </div>
            <div class="col-md-6">
                <div class="float-md-right">
                    <ol class="breadcrumb mb-0 p-0 bg-transparent ">
                        <li class="breadcrumb-item"><a href="{{ url('/doctor/dashboard') }}" >Dashboard</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Profile</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
    <div class="doctor-profile pt-4">
        <div class="card">
            <div class="card-header py-2">
                Basic Info
            </div>
            <div class="card-body">
                <form method="POST" action="{{ route('doctor.profile.update',$doctor->doctor->id) }}" class="register-validation" novalidate enctype="multipart/form-data">
                    @csrf
                    <div class="card border-0">
                        <div class="card-body ">

                            <div class="form-group row">
                                <label for="inputPassword" class="col-sm-2 col-form-label">Title</label>
                                <div class="col-sm-10">
                                    <input type="text" name="title" value="{{ $doctor->doctor->title }}" class="form-control" id="inputPassword" placeholder="Enter Title">
                                </div>
                                <div class="invalid-feedback" role="alert">
                                    <strong>Please enter title</strong>
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="inputPassword" class="col-sm-2 col-form-label">Phone</label>
                                <div class="col-sm-10">
                                    <input type="number" name="phone" value="{{ $doctor->doctor->phone }}" class="form-control" id="inputPassword" placeholder="Enter Phone No">
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="validationCustom04" class="col-sm-2 col-form-label">Department </label>
                                <div class="col-sm-10">
                                    <select class="custom-select form-control" id="validationCustom04" name="department_id" >
                                        <option  disabled value="">--Select One--</option>
                                        @foreach($departments as $department)
                                            <option value="{{ $department->id }}" {{($doctor->doctor->department_id == $department->id)?'selected':''}}>{{ $department->name }}</option>
                                        @endforeach

                                    </select>
                                </div>

                            </div>

                            <div class="form-group row">
                                <label for="inputPassword" class="col-sm-2 col-form-label">Fees</label>
                                <div class="col-sm-10">
                                    <input type="number" name="fees" value="{{ $doctor->doctor->fees }}" class="form-control" id="inputPassword" placeholder="Enter your fees">
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="inputPassword" class="col-sm-2 col-form-label">Experience</label>
                                <div class="col-sm-10">
                                    <input type="number" name="year_of_experience" value="{{ $doctor->doctor->year_of_experience }}" class="form-control" id="year_of" placeholder="Year Of Experience">
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="inputPassword" class="col-sm-2 col-form-label">Describe Yourself</label>
                                <div class="col-sm-10">
                                    <textarea class="joditeditor  form-control" name="describe_yourself" id="exampleFormControlTextarea1" rows="5" placeholder="Write your description...">
                                        {{ $doctor->doctor->describe_yourself }}
                                    </textarea>
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="inputPassword" class="col-sm-2 col-form-label">Chamber Address</label>
                                <div class="col-sm-10">
                                    <textarea class="joditeditor form-control" name="chamber_information" id="exampleFormControlTextarea1" rows="5" placeholder="Your Chamber location...">
                                        {{ $doctor->doctor->chamber_information }}
                                    </textarea>
                                </div>
                            </div>


                            <div class="form-group row">
                                <label for="inputPassword" class="col-sm-2 col-form-label">Photo</label>
                                <div class="col-sm-10">
                                    <div class="custom-file mb-3">
                                        <input type="file" name="photo" class="custom-file-input @error('photo') is-invalid @enderror" id="photo" >
                                        <label class="custom-file-label" for="validatedCustomFile">Choose file...</label>
                                        @error('photo')
                                        <p class="alert alert-danger">{{ $message }}</p>
                                        @enderror
                                    </div>
                                </div>
                            </div>

                            <div class="form-group row">
                                <div class="col-sm-2"></div>
                                <div class="col-sm-10">
                                    <button type="submit" class="btn btn-block btn-primary">Update Profile</button>
                                </div>
                            </div>


                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>

@endsection